uint64      timestamp                     # Timestamp when message is sent via ROS

float32     exterior_rain_intensity       # Detected exterior rain intensity [%]                                  
float32     exterior_temperature          # Measured exterior temperature [°C]           
float32     exterior_light_illumination   # Measured exterior light illumination [Lux]
float32     exterior_road_grade           # Measured exterior road slope [%]