uint64                  timestamp           # Timestamp when message is sent via ROS

FrontObject       front_object_1       # Front object 1 of vehicle sensor CAN objects
FrontObject       front_object_2       # Front object 2 of vehicle sensor CAN objects
FrontObject       front_object_3       # Front object 3 of vehicle sensor CAN objects
FrontObject       front_object_4       # Front object 4 of vehicle sensor CAN objects