uint64           timestamp          # Timestamp when message is sent via ROS

RearObject       rear_object_1       # Rear object 1 of vehicle sensor CAN objects
RearObject       rear_object_2       # Rear object 2 of vehicle sensor CAN objects
RearObject       rear_object_3       # Rear object 3 of vehicle sensor CAN objects
RearObject       rear_object_4       # Rear object 4 of vehicle sensor CAN objects
RearObject       rear_object_5       # Rear object 5 of vehicle sensor CAN objects
RearObject       rear_object_6       # Rear object 6 of vehicle sensor CAN objects