uint64  timestamp          # timestamp when message is sent via ros

uint8   traffic_sign1        # traffic sign 1 value - see vehicle can documentation for more details
uint8   additional_sign1     # additional information for traffic sign 1 - see vehicle can documentation for more details    
uint8   source_sign1         # source of traffic sign 1 value and additional information - 0 = none, 1 = camera, 2 = map, 3 = law

uint8   traffic_sign2        # traffic sign 2 value - see vehicle can documentation for more details 
uint8   additional_sign2     # additional information for traffic sign 2 - see vehicle can documentation for more details 
uint8   source_sign2         # source of traffic sign 2 value and additional information - 0 = none, 1 = camera, 2 = map, 3 = law

uint8   traffic_sign3        # traffic sign 3 value - see vehicle can documentation for more details 
uint8   additional_sign3     # additional information for traffic sign 3 - see vehicle can documentation for more details    
uint8   source_sign3         # source of traffic sign 3 value and additional information - 0 = none, 1 = camera, 2 = map, 3 = law 

uint8   traffic_sign4        # traffic sign 4 value - see vehicle can documentation for more details 
uint8   additional_sign4     # additional information for traffic sign 4 - see vehicle can documentation for more details    
uint8   source_sign4         # source of traffic sign 4 value and additional information - 0 = none, 1 = camera, 2 = map, 3 = law

uint8   traffic_sign5        # traffic sign 5 value - see vehicle can documentation for more details 
uint8   additional_sign5     # additional information for traffic sign 5 - see vehicle can documentation for more details    
uint8   source_sign5         # source of traffic sign 5 value and additional information - 0 = none, 1 = camera, 2 = map, 3 = law