bool cc_mux               # Indicates if cancel conditions or activation prevention reasons ar transmitted

bool ap_ign_off           
bool c_ign_off

bool ap_engine_off
bool c_engine_off

bool ap_acc_main_off
bool c_acc_main_off

bool ap_cgw_error
bool c_cgw_error

bool ap_epb_engaged
bool c_epb_engaged

bool ap_no_sw_clearance
bool c_no_sw_clearance

bool ap_customer_cancelation
bool c_customer_cancelation

bool ap_vgw_not_standby
bool c_vgw_not_standby

bool ap_vgw_cancelation
bool c_vgw_cancelation

bool ap_critical_state
bool c_critical_state

bool ap_driver_intervention
bool c_driver_intervention

bool ap_invalid_speed
bool c_invalid_speed

bool ap_invalid_gear
bool c_invalid_gear

bool ap_locked_interface
bool c_locked_interface

bool ap_vgw_not_follow
bool c_vgw_not_follow

bool ap_invalid_user_data
bool c_invalid_user_data

bool ap_vgw_error
bool c_vgw_error

bool ap_invalid_vgw_data
bool c_invalid_vgw_data

bool ap_actuator_error
bool c_actuator_error

bool ap_invalid_vehicle_data
bool c_invalid_vehicle_data
